from pathlib import Path
from openpyxl import Workbook


BASE_FOLDER = Path("knowledge/master_data")


FILES = {

    "aluminium_raw_materials.xlsx": [

        "Material ID",
        "Material Name",
        "Family",
        "Category",
        "Form",
        "Grade",
        "Produced By",
        "Used By",
        "Manufacturing Process",
        "Possible Finished Products",
        "Possible Scrap Generated",
        "Estimated Monthly Consumption (MT)",
        "Confidence",
        "Source",
        "Remarks"

    ],

    "aluminium_semi_finished_products.xlsx": [

        "Product ID",
        "Product Name",
        "Family",
        "Category",
        "Grade",
        "Manufactured By",
        "Used By",
        "Next Manufacturing Process",
        "Applications",
        "Confidence",
        "Source",
        "Remarks"

    ],

    "aluminium_finished_products.xlsx": [

        "Product ID",
        "Product Name",
        "Category",
        "Industry",
        "Application",
        "Grade",
        "Manufacturing Process",
        "Raw Material Used",
        "Possible Scrap Generated",
        "Confidence",
        "Source",
        "Remarks"

    ],

    "aluminium_scrap.xlsx": [

        "Scrap ID",
        "Scrap Name",
        "Category",
        "Grade",
        "Generated By",
        "Manufacturing Process",
        "Can Be Recycled Into",
        "Typical Recovery %",
        "Estimated Monthly Qty (MT)",
        "Confidence",
        "Source",
        "Remarks"

    ],

    "aluminium_grades.xlsx": [

        "Grade",
        "Standard",
        "Series",
        "Description",
        "Typical Use",
        "Remarks"

    ],

    "aluminium_alloys.xlsx": [

        "Alloy",
        "Series",
        "Standard",
        "Base Metal",
        "Major Elements",
        "Typical Use",
        "Remarks"

    ],

    "aluminium_processes.xlsx": [

        "Process ID",
        "Process Name",
        "Input Material",
        "Output Product",
        "Typical Scrap",
        "Typical Yield %",
        "Remarks"

    ],

    "aluminium_industries.xlsx": [

        "Industry ID",
        "Industry Name",
        "Products",
        "Raw Materials",
        "Scrap Generated",
        "Remarks"

    ],

    "aluminium_machinery.xlsx": [

        "Machine ID",
        "Machine Name",
        "Industry",
        "Manufacturing Process",
        "Input Material",
        "Output Product",
        "Remarks"

    ],

    "aluminium_recycling.xlsx": [

        "Step ID",
        "Recycling Step",
        "Input",
        "Output",
        "Remarks"

    ],

    "aluminium_process_flow.xlsx": [

        "Flow ID",
        "Raw Material",
        "Manufacturing Process",
        "Finished Product",
        "Scrap Generated",
        "Recycling Route"

    ],

    "aluminium_intelligence_rules.xlsx": [

        "Rule ID",
        "Business Type",
        "Consumes",
        "Produces",
        "Generates",
        "Sell Opportunity",
        "Buy Opportunity",
        "Confidence"

    ]

}


def create_excel(file_name, headers):

    wb = Workbook()

    ws = wb.active

    ws.title = "Master Data"

    ws.append(headers)

    for cell in ws[1]:

        cell.font = cell.font.copy(bold=True)

    wb.save(BASE_FOLDER / file_name)

    print(f"✓ Created : {file_name}")


def main():

    BASE_FOLDER.mkdir(parents=True, exist_ok=True)

    print()

    print("=" * 60)

    print("CREATING METALENGINE MASTER DATA")

    print("=" * 60)

    print()

    for file_name, headers in FILES.items():

        create_excel(file_name, headers)

    print()

    print("=" * 60)

    print("MASTER DATA CREATED SUCCESSFULLY")

    print("=" * 60)


if __name__ == "__main__":

    main()